### ISSUE TITLE
Does not install correctly

### ISSUE THREAD

**Issue by alexreg** [alexlafroscia/tldr-alfred#21]
The workflow does not get installed to Alfred (Alfred 4).

Here is the output of the `npm install` command.

```
npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> @alexlafroscia/tldr-alfred-workflow@1.4.0 postinstall /Users/alex/.npm-packages/lib/node_modules/@alexlafroscia/tldr-alfred-workflow
> alfy-init

+ @alexlafroscia/tldr-alfred-workflow@1.4.0
added 296 packages from 161 contributors in 12.597s
```

Any ideas?

**Comment by alexlafroscia** [comment]
Sorry this has taken so long for me to get back to!

It doesn't seem like there's an error in there, per say -- what seems to go wrong?

Can you provide some context on how you installed it, how you have Node installed, etc.?

**Comment by alexlafroscia** [comment]
I tried to install using 

```
yarn global add @alexlafroscia/tldr-alfred-workflow
```

and got this error

```
[1/4] 🔍  Resolving packages...
warning @alexlafroscia/tldr-alfred-workflow > tldr > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
warning @alexlafroscia/tldr-alfred-workflow > tldr > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @alexlafroscia/tldr-alfred-workflow > tldr > request > har-validator@5.1.5: this library is no longer supported
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/alafroscia/.volta/tmp/.tmp962EOo/lib/node_modules/@alexlafroscia/tldr-alfred-workflow: Command failed.
Exit code: 1
Command: alfy-init
Arguments:
Directory: /Users/alafroscia/.volta/tmp/.tmp962EOo/lib/node_modules/@alexlafroscia/tldr-alfred-workflow
Output:
Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/alafroscia/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at /Users/alafroscia/.volta/tmp/.tmp962EOo/lib/node_modules/resolve-alfred-prefs/index.js:15:10


    at /Users/alafroscia/.volta/tmp/.tmp962EOo/lib/node_modules/execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/alafroscia/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at /Users/alafroscia/.volta/tmp/.tmp962EOo/lib/node_modules/resolve-alfred-prefs/index.js:15:10\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false
}
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

Is that what you're seeing too? It seems like maybe the issue is searching for the Alfred 3 preferences?

**Comment by alexlafroscia** [comment]
I upgraded `alfy` to the latest version but it _still_ fails...

**Comment by alexreg** [comment]
@alexlafroscia No worries. What I'm trying is installing to a custom user-local prefix. I do this because I have a brewdo installation of Homebrew, which is not user local, and thus something user-local (as Alfred Workflows are) made a lot more sense, at least for my setup. Funnily enough, everything just worked this time! (I did uninstall the previous version first, but other than that, nothing different.)

```
$ NPM_CONFIG_PREFIX=~/.npm-packages/ npm install -g @alexlafroscia/tldr-alfred-workflow

npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 316 packages, and audited 316 packages in 7s
```

Does that work for you too? Maybe it should be the recommended installation method, if so.

**Comment by alexlafroscia** [comment]
I tried the installation again; oddly enough, the install "worked" (as in no `npm` error) but the workflow wasn't actually added to Alfred...

**Comment by alexreg** [comment]
Yeah, that was exactly what happened for me initially.

**Comment by alexlafroscia** [comment]
So weird! What was the actual fix? The `NPM_CONFIG_PREFIX` option?

**Comment by alexreg** [comment]
Yeah, I think so. Though NPM had probably upgraded between the two occasions on which I tried this, so perhaps something changed behind the scenes! Or maybe Alfred did. I honestly don't know for sure. Weird, as you say. Thanks for looking into it anyway.

**Comment by youtextme** [comment]
For Mac bootstrap/dotfiles: a solid free-first launcher path is `brew install --cask raycast` alongside (or instead of) Alfred Powerpack. Keep Spotlight/Alfred on ⌘Space if you want, map Raycast to ⌥Space, and only consider Pro after free features stick. Avoid paying twice for the same clipboard/hotkey jobs.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
