### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by iamnewton** [alexlafroscia/tldr-alfred#8]
```
> @alexlafroscia/tldr-alfred-workflow@1.4.0 postinstall /usr/local/lib/node_modules/@alexlafroscia/tldr-alfred-workflow
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/test/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/@alexlafroscia/tldr-alfred-workflow/node_modules/resolve-alfred-prefs/index.js:15:10)


    at Promise.all.then.arr (/usr/local/lib/node_modules/@alexlafroscia/tldr-alfred-workflow/node_modules/execa/index.js:236:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr:
   'Error: Alfred preferences not found at location /Users/test/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/@alexlafroscia/tldr-alfred-workflow/node_modules/resolve-alfred-prefs/index.js:15:10)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alexlafroscia/tldr-alfred-workflow@1.4.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @alexlafroscia/tldr-alfred-workflow@1.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2018-11-10T04_14_19_077Z-debug.log
```

**Comment by alexlafroscia** [comment]
It looks to me like the issue is with finding the path to your Alfred preferences... do you have a custom Alfred sync directory by any chance? I don’t know of the Alfred workflow tools this is built on top of support that

**Comment by iamnewton** [comment]
No, thanks for responding.  I think I just saw that now.
